name: backend
description: Linux Backend of Web-based UI for Delta Robot - Compas Agro.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  http: ^0.13.3
  dart_amqp: ^0.2.5
  uuid: ^4.4.0
  shelf: ^1.4.1
  web_socket_channel: ^2.4.5
  shelf_web_socket: ^1.0.4
  shelf_cors_headers: ^0.1.5

dev_dependencies:
