name: windows
description: Web-based UI for Delta Robot - Compas Agro.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - assets/images/
    - assets/static/images/
    - .env
  uses-material-design: true