name: Flutter Web CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      my_secret: ${{secrets.GH_DEPLOY}}
    steps:
    - uses: actions/checkout@v1
    - name: Install Flutter
      run: |
        sudo apt-get update
        sudo apt-get install curl
        curl https://storage.googleapis.com/flutter_infra/releases/stable/linux/debian/flutter_linux_2.10.4-stable.tar.xz | tar xf -
        export PATH="$PATH:`pwd`/flutter/bin"
    - name: Verify Flutter Installation
      run: flutter doctor
    - run: cd User_Interface/frontend && flutter config --enable-web
    - run: cd User_Interface/frontend && flutter pub get
    - run: cd User_Interface/frontend && flutter build web
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: web-build
        path: User_Interface/frontend/build/web
    - name: Download Artifact
      uses: actions/download-artifact@master
      with:
        name: web-build 
    - name: Display structure of build files
      run: ls -R
      working-directory: ./User_Interface/frontend/web
    - name: Deploy to GH Pages
      run: |
        cd User_Interface/frontend/build/web
        git init
        git config --global user.email ranubhardwaj89@gmail.com
        git config --global user.name himanshusharma89
        git status
        git remote add origin https://${{secrets.GH_DEPLOY}}@github.com/himanshusharma89/dev.git
        git checkout -b gh-pages
        git add --all
        git commit -m "update"
        git push origin gh-pages -f
