name: Build and Deploy to Main Branch

on:
  push:
    branches:
      - main
    paths:
      - 'User_Interface/frontend/lib/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cedvdb/action-flutter-build-web@v1
        with:
          build-cmd: flutter build web --release
          working-directory: User_Interface/frontend/

      - name: Create temporary branch
        id: temp_branch
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git checkout -b temp-branch
          git pull -b temp-branch

      - name: Commit changes
        run: |
          git add User_Interface/frontend/build/web/* -f
          git commit -m "Deploy build to main"
          
      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"

      - name: Push changes to temporary branch
        run: |
          git push origin temp-branch

      - name: Merge temporary branch into main
        run: |
          git checkout main
          git merge --no-edit temp-branch

      - name: Delete temporary branch
        run: gh pr delete ${{ github.event.pull_request.number }} --confirm

      - name: Update main branch
        run: |
          git fetch origin main
          git reset --hard origin/main
