name: Build and distribute

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cedvdb/action-flutter-build-web@v1
        with:
          build-cmd: flutter build web --release
          working-directory: User_Interface/frontend/

      - name: Archive Production artifact
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: build/web
