name: Build and Deploy to Main Branch

on:
  push:
    branches:
      - main
    paths:
      - 'User_Interface/frontend/lib/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cedvdb/action-flutter-build-web@v1
        with:
          build-cmd: flutter build web --release
          working-directory: User_Interface/frontend/

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create or Reset Temporary Branch
        run: |
          git checkout main
          git checkout -B temp-branch
          git push -f origin temp-branch

      - name: Commit changes
        run: |
          git add User_Interface/frontend/build/web/* -f
          git commit -m "Deploy build to main" || echo "No changes to commit"

      - name: Push changes to temporary branch
        run: |
          git push -f origin temp-branch

      - name: Merge temporary branch into main
        run: |
          git checkout main
          git merge --strategy-option theirs temp-branch
          git push origin main

      - name: Delete temporary branch
        run: |
          git push origin --delete temp-branch

      - name: Update main branch
        run: |
          git fetch origin main
          git reset --hard origin/main
